-- Schema già gestito in Supabase. Questo file è solo documentazione.
-- Non eseguire le vecchie policy: il database esistente comprende:
-- public.chronoself_saves (payload personale, RLS per user_id)
-- public.chronoself_entitlements (lettura propria; scrittura solo server)
-- public.chronoself_billing_events (event_id univoco)
-- public.apply_chronoself_billing_event(...) (solo service_role)
-- private.enforce_chronoself_entitlement() (pro derivato dal server)
-- Nessuna migrazione o modifica ai dati è richiesta da questo aggiornamento.
